monolog:
  handlers:
    main:
      type: rotating_file
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      max_files: 3
      channels: ["!event", "!deprecation", "!elasticsearch"]
    deprecations:
      type: rotating_file
      path: "%kernel.logs_dir%/%kernel.environment%_deprecation.log"
      level: debug
      max_files: 3
      channels: ["deprecation"]
    elasticsearch:
      type: rotating_file
      path: "%kernel.logs_dir%/%kernel.environment%_search.log"
      level: warning
      max_files: 3
      channels: [ "search" ]
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine", "!console", "!deprecation", "!elasticsearch"]
