monolog:
  channels: ['deprecation']
  handlers:
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      channels: ["!event"]
    nested:
      type: rotating_file
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      max_files: 3
    deprecations:
      type: rotating_file
      path: "%kernel.logs_dir%/%kernel.environment%_deprecation.log"
      level: debug
      max_files: 3
      channels: ["deprecation"]
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine", "!console", "!deprecation"]
