name: Update Flex endpoint

on:
  push:
    branches:
      - main
      - feature/SHOPWARE-119*

defaults:
  run:
    shell: bash

jobs:
  call-flex-update:
    uses: symfony/recipes/.github/workflows/callable-flex-update.yml@main
    with:
      branch: main
      contrib: true